version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    env_file:
      - database.env
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
